version: '3.8'

services:
    web:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        volumes:
            - static_volume:/srv/static
            - media_volume:/srv/media
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - private
        restart: unless-stopped

    db:
        image: postgres:14.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.db
        networks:
            - private
        restart: unless-stopped

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/srv/static
            - media_volume:/srv/media
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.gazette-secure.entrypoints=https"
            - "traefik.http.routers.gazette-secure.rule=Host(`gazette.teamna.me`)"
            - "traefik.http.routers.gazette-secure.tls=true"
            - "traefik.http.routers.gazette-secure.service=nginx-gazette@docker"
            - "traefik.docker.network=traefik-proxy"
        depends_on:
            - web
        networks:
            - private
            - public
            - traefik-proxy
        restart: unless-stopped

networks:
    private:
        driver: overlay
    public:
        external: true
    traefik-proxy:
        external: true

volumes:
    postgres_data:
    static_volume:
    media_volume:
